version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 5000:80     
      - 8081:8080  # Traefik's web UI, enabled by --api
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock  
  app:
    build: app
    volumes:
        - ./app:/app
    scale: 4
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`localhost`)"
    expose: 
        - 5000